---
- name: Install selinux management dependencies
  ansible.builtin.package:
    state: present
    name:
      - python3-libsemanage
      - python3-libselinux

- name: Enforce selinux
  ansible.posix.selinux:
    policy: targeted
    state: enforcing

- name: Selinux configuration for nginx
  ansible.posix.seboolean:
    name: httpd_{{ item }}
    state: true
    persistent: true
  loop:
    - can_network_relay
    - use_nfs
