---

- name: install selinux management dependencies
  package:
    state: present
    name:
      - python3-libsemanage
      - python3-libselinux

- name: enforce selinux
  selinux:
    policy: targeted
    state: enforcing

- name: selinux configuration for nginx
  seboolean:
    name: httpd_{{ item }}
    state: true
    persistent: true
  loop:
    - can_network_relay
    - use_nfs
